function temporalDefualt = st_temporal_default(temporalModel)


switch temporalModel
    case 'None'
        temporalDefualt = struct(...
            'type', 'None', ...
            'fs', 1000, ... % sampling rate
            'fields',[],...
            'num_channels', [], ...
            'prm', [], ...
            'searchRange', []...
            );  
    case '1ch-dcts'
        % 1ch-dcts
        % {'tau1', 'weight', 'tau2', 'n', 'sigma', 'shift', 'scale'};
        temporalDefualt = struct(...
            'type', '1ch-dcts', ...
            'fs', 1000, ... % sampling rate
            'fields',["tau1", "weight", "tau2", "nn", "delay", "shift", "scale"],...
            'num_channels', 1, ...
            'prm', [0.05 0 0.1 2 0.1 0 1], ...
            'searchRange',   [0.07  0  0.07 1  0.01 0 0; 1  0  1    6  0.5 0 0]...
            );  %   'prm', [0.05 0 0.1 2 0.1 0 1] ...
        
    case '2ch-exp-sig'
        
        %  2ch-exp-sig
        %  {'tau_s', 'tau_ae', 'lambda_p', 'kappa_p', 'kappa_n', 'weight','shift'};
        %  searchRange: row1 = lowerRange, row2 = upperRange,
        %               col  = params
        temporalDefualt = struct(...
            'type', '2ch-exp-sig', ...
            'fs', 1000, ...
            'num_channels', 2, ...,
            'fields', ["tau_s", "tau_ae", "Lp", "Kp", "Kn", "weight","shift"], ...
            'prm', [4.93 10000 0.1 3 3 0.5 0], ...
            'searchRange', [4  1 .01 .1 .1 0 0; 20 8 .5  7 7 0 0 ] ...
            );
        
    case '1ch-glm'
        
        %  1ch-glm (linear)
        %  {'shift','scale'};
        temporalDefualt = struct(...
            'type', '1ch-glm', ...
            'fs', 1000, ...
            'fields',["shift", "scale"],...
            'num_channels', 1, ...
            'prm', [0 1], ...
            'searchRange',  [0 0; 0 0]...
            );
        
end