#! /bin/bash
#
#

CONTAINER="[garikoitz/prfsynth]"
echo -e "$CONTAINER  Initiated"


# Built to flywheel-v0 spec.
FLYWHEEL_BASE=/flywheel/v0
MCR_ROOT=/opt/mcr/v95/
OUTPUT_DIR=$FLYWHEEL_BASE/output


# Make sure that /output directory exists
if [[ ! -d "$OUTPUT_DIR" ]]
    then
        echo "$CONTAINER  $OUTPUT_DIR not found!"
        exit 1
fi


# Set paths to input files
CONFIG_FILE=${FLYWHEEL_BASE}/input/config.json


# Run the Matlab executable
time /compiled/run_synthBOLDgenerator.sh "${MCR_ROOT}" "${CONFIG_FILE}" "${OUTPUT_DIR}"


# Check exit status
exit_status=$?
if [[ $exit_status != 0 ]]; then
  echo -e "$CONTAINER  An error occurred during execution of the Matlab executable. Exiting!"
  exit 1
fi


# Get a list of the files in the output directory
# outputs=$(find $OUTPUT_DIR/* -maxdepth 0 -type f)
outputs=$(find $OUTPUT_DIR/* )


# If outputs exist, generate metadata, and exit
if [[ -z $outputs ]]; then
  echo "$CONTAINER  No results found in output directory... Exiting"
  exit 1
else
  cd $OUTPUT_DIR
  echo -e "$CONTAINER  Available synth datasets: `ls`"
  echo -e "$CONTAINER  Done!"
fi


# Handle permissions of the outputs
chmod -R 777 $OUTPUT_DIR


# Exit
exit 0
